force-app/main/default/objects/Geocoding_Config__mdt/Geocoding_Config__mdt.object-meta.xml
<CustomObject>
    <label>Geocoding Config</label>
    <pluralLabel>Geocoding Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Geocoding_Config__mdt/fields/API_Key__c.field-meta.xml
<CustomField>
    <fullName>API_Key__c</fullName>
    <label>API_Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Geocoding_Config__mdt/fields/Open_Cage_URL__c.field-meta.xml
<CustomField>
    <fullName>Open_Cage_URL__c</fullName>
    <label>Open Cage URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/GeocodingConfigSelector.cls
public with sharing class GeocodingConfigSelector {
  private static final String GEOCODE_ERROR_MESSAGE = 'Geocoding_Config__mdt record "OpenCage" missing or has no key or has no url.';
  public static Geocoding_Config__mdt getGeocodingConfig() {
    List<Geocoding_Config__mdt> result = [
      SELECT Api_Key__c, Open_Cage_URL__c
      FROM Geocoding_Config__mdt
      WHERE DeveloperName = 'OpenCage'
      LIMIT 1
    ];
    if (
      result.isEmpty() ||
      String.isBlank(result[0].Api_Key__c) ||
      String.isBlank(result[0].Open_Cage_URL__c)
    ) {
      throw new MDTCustomException(GEOCODE_ERROR_MESSAGE);
    }
    return result[0];
  }
}