force-app/main/default/objects/Mistral_Config__mdt/Mistral_Config__mdt.object-meta.xml
<CustomObject>
    <label>Mistral Config</label>
    <pluralLabel>Mistral Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Mistral_Config__mdt/fields/Api_Key__c.field-meta.xml
<CustomField>
    <fullName>Api_Key__c</fullName>
    <label>Api Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mistral_Config__mdt/fields/Mistral_Batch_URL__c.field-meta.xml
<CustomField>
    <fullName>Mistral_Batch_URL__c</fullName>
    <label>Mistral Batch URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/MistralConfigSelector.cls
public with sharing class MistralConfigSelector {
  private static final String MISTRAL_ERROR_MESSAGE = 'Mistral_Config__mdt record "MistralBatch" missing or has no key or has no url.';
  public static Mistral_Config__mdt getMistralConfig() {
    List<Mistral_Config__mdt> result = [
      SELECT Api_Key__c, Mistral_Batch_URL__c
      FROM Mistral_Config__mdt
      WHERE DeveloperName = 'MistralBatch'
      LIMIT 1
    ];
    if (
      result.isEmpty() ||
      String.isBlank(result[0].Api_Key__c) ||
      String.isBlank(result[0].Mistral_Batch_URL__c)
    ) {
      throw new MDTCustomException(MISTRAL_ERROR_MESSAGE);
    }
    return result[0];
  }
}